application: Risk Game
version: 1
deploy: true
pub: true
dart2js: true

handlers:
- url: /ws
  handler: risk.dart:Risk

- url: /new
  match: exact
  script: risk.dart.dart
  handler: NewGame

# Static content, will be served by your app's Nginx instance
- url: /
  match: postregex
  static_dir: web
